### ISSUE TITLE
Cant find xml2yolo.py

### ISSUE THREAD

**Issue by JaumePrats** [dongjuns/RoadDamageDetector#1]
In **Dongjuns_IEEE_BDC_GRDD_2020.ipynb** when transforming to YOLO format **xml2yolo.py** is used but it does not exist in the directory.

**Comment by dongjuns** [comment]
@JaumePrats 
Hi, JaumePrats. On the other way, I think you can find the file 'xml2yolo.py' here, use it this way.
<https://github.com/dongjuns/RoadDamageDetector/blob/master/xml2yolo.py>
