### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by ashugorthy** [dongjuns/RoadDamageDetector#2]
I have tried to run your code in Google Colab. While the respective files were generated and stored in the "road" folder, I was unable to find the 'YAML files, train.py, and road_detect.py
Since I am running in Colab, which does not support docker, I opted for Method 2, but it requires all the above-mentioned files. Please let me know where I can find them.
Thank you for the help.

**Comment by dongjuns** [comment]
@ashugorthy 
I think setting the docker is the easiest way than others.
Or, install the YOLOv5 <https://github.com/ultralytics/yolov5> in your environment, like a Colab.

Then, you need to make it correct the path of the files in your Colab using pwd.

**Comment by dongjuns** [comment]
@ashugorthy Hi, here is the zip file.
<https://drive.google.com/drive/folders/1K61pO8g9TuzZ76QR2TOVUHPsHBc77TLE?usp=sharing>

**Comment by ashugorthy** [comment]
@dongjuns Thank you so much for the help. I will check this out.

**Comment by curry30-star** [comment]
where can i get your paper ?
<img width="751" alt="image" src="https://github.com/dongjuns/RoadDamageDetector/assets/147220071/abcacf81-1c10-4315-835b-887b5a84b057">

**Comment by dongjuns** [comment]
@curry30-star Here you are.
https://www.researchgate.net/publication/346787656_Road_Damage_Detection_Using_YOLO_with_Smartphone_Images

**Comment by curry30-star** [comment]
Thank you for your prompt reply


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dongjuns/RoadDamageDetector"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月7日(星期六) 上午10:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [dongjuns/RoadDamageDetector] Missing files (#2)





 
@curry30-star Here you are.
 https://www.researchgate.net/publication/346787656_Road_Damage_Detection_Using_YOLO_with_Smartphone_Images

**Comment by dongjuns** [comment]
@curry30-star No problem. I hope you get a good result!
